Localization: en

# Main Settings of cauldron
Cauldron:
  secondstoboil: 10 # Seconds to boil
  blocktoupgrage: iron_block # Click on block to upgrade. If you want craft in cauldron without upgrade. Just leave this empty
  maxitemsincauldron: 32 # How much items cauldron can take

# Event PlayerDropItem and checks where item is to drop in cauldron
# You can just forget about it
dropitem:
  checknearbycauldron:
    delay: 5
    radius: 0.1
    secondstocheck: 20

# Holograms in SUPER ALPHA!!!!
Hologram:
  enabled: false
  visiblinradius:
    enabled: true
    radius: 10
  floating:
    enabled: true
    distance: 0.2

# Don't touch
configversion: 0.1