Localization: en

# Main Settings of cauldron
Cauldron:
  secondsToBoil: 10 # Seconds to boil
  blockToUpgrage: iron_block # Click on block to upgrade. If you want craft in cauldron without upgrade. Just leave this empty
  maxItemsInCauldron: 32 # How much items cauldron can take

# Event PlayerDropItem and checks where item is to drop in cauldron
# You can just forget about it
dropItem:
  checkNearByCauldron:
    delay: 5
    radius: 0.1
    secondsToCheck: 20

# Holograms in SUPER ALPHA!
Hologram:
  enabled: false
  visibleInRadius:
    enabled: true
    radius: 10
  floating:
    enabled: true
    distance: 0.2

# Don't touch
configVersion: 0.11