name: Java CI

on:
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]

jobs:
  build:

    runs-on: ubuntu-16.04
  
    strategy:
      matrix:
        java: [11, 8]

    steps:
    - uses: actions/checkout@v2.1.0

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1.4.3
      with:
        java-version: ${{ matrix.java }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: actions/upload-artifact@v2
      with:
        name: CauldronBrew-JDK${{ matrix.java }}
        path: ./target/*.jar
